# Deployment Pipeline for Healthcare
# https://aka.ms/yaml

trigger:
- none

pool:
  name: 'selfhosted-agentpool'

variables:
- group: 'sample'

stages:
- stage: CloneGHE
  jobs:
  - job: CloneGHE
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'cd $(Agent.BuildDirectory)'
          cd $(Agent.BuildDirectory)
          echo 'mkdir $(github_repo)'
          mkdir $(github_repo)
          git config --global url."https://$(github_pat)@github.build.ge.com/".insteadOf https://github.build.ge.com/
          echo 'Git Clone'
          git clone -b https://$(User_SSO):$(github_pat)github.build.ge.com/$(github_org)/$(github_repo).git "$(Agent.BuildDirectory)/$(github_repo)"
          echo $(Agent.BuildDirectory)
          echo $(github_repo)
          echo $(Build.SourcesDirectory)

