# Deployment Pipeline for Healthcare
# https://aka.ms/yaml

trigger:
- none

pool:
  name: 'selfhosted-agentpool'

stages:
- stage: ConnectGHE
  jobs:
  - job: ConnectGHE
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          git config --global url."https://$(github_pat)@github.build.ge.com/".insteadOf https://github.build.ge.com/
          git clone -b $(github_branch) https://github.build.ge.com/$(github_org)/$(github_repo).git "$(Agent.BuildDirectory)/$(github_repo)"
          displayName: 'git clone'
          echo 'Hello world'
